### ISSUE TITLE
yaml problems?

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/Basics#1]
don't think the   "../module-1-git/module-1-git-intro.Rmd", line is correct in the yaml?  That file doesn't exist as far as I can tell? However, I can't compile at all now, so not sure where the error is

**Comment by andrew-edwards** [comment]
Think we can close. There are some warnings but they're fine.

**Comment by andrew-edwards** [comment]
@kcudding - I did notice there's some YAML stuff at the start of your two modules (I think). Probably not needed (since bookdown and it's all at the start), but everything seems to work so probably not worth messing with either.

**Comment by kcudding** [comment]
?? I have no yaml stuff. I do have some r chunk stuff, is that what you mean?

**Comment by andrew-edwards** [comment]
Hmmm... you're right. Maybe it was this that I saw:
https://github.com/quantitative-biology/module-5-optimization/blob/main/Module5_solutions.Rmd
though if it's not part of the build then that's fine. I'll close.
