### ISSUE TITLE
short alt text for all figures

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/Basics#16]
B. Items we should try to address for AODA
9. alt text describing figures should not be too long (two lines at most), but more material in the
figure captions

**Comment by kcudding** [comment]
we have some fig.alts generated by undergrad for approval and addition

**Comment by kcudding** [comment]
mods 3 & 5 are done

**Comment by andrew-edwards** [comment]
Git and Rmarkdown modules all have alt text (and captions).

**Comment by kcudding** [comment]
mod 4 done
