### ISSUE TITLE
Remove internal hash tags on headings

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/Basics#19]
B. Items we should try to address for AODA

11. Hash tag that appears beside internal headings should be removed (Me: no idea if possible)

**Comment by kcudding** [comment]
currently replaced with "(internal link)", can eliminate or replace with different symbol

**Comment by kcudding** [comment]
or replace with nothing

**Comment by andrew-edwards** [comment]
Great. My friend I mentioned the other day actually got stuck on that, saying the links didn't work. The explicit links can be useful for someone to get the url to refer to a specific section.
