### ISSUE TITLE
Suggest adding  a note about Web Accessibility in Introduction

### ISSUE THREAD

**Issue by andrew-edwards** [quantitative-biology/Basics#22]
After '1.1 Open Science', could have something like:

1.2 Web accessibility

We have strived to make this teaching tool accessible to those with accessibility issues. For example, all figures have captions plus alternate text that should get read out by a screen reader, and colour-blind-proof colour palettes have been used as much as possible.

Or something like that (@kcudding may have something more concrete).

**Comment by kcudding** [comment]
done
