### ISSUE TITLE
fig.alt captions

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/Basics#3]
We need to include previously created/copied figures as

{r, echo=FALSE, out.height="50%", fig.cap="name of fig", fig.alt="descript of fig"}
knitr::include_graphics("thermalperform.jpg")

??? maybe

so we have alt text AND correct addressing

**Comment by kcudding** [comment]
fixed this for mod 2 reference, but still need fig.alt descriptions

**Comment by andrew-edwards** [comment]
Closing, as duplicated by #12 (and #13).
