### ISSUE TITLE
suggest adding link to this github in bookdown book

### ISSUE THREAD

**Issue by trashbirdecology** [quantitative-biology/Basics#7]
It may be buried in there somewhere, but I couldn't find a URI to this repository within the bookdown book. I suggest putting at bottom, top, or frontmatter or somewhere else obvious.

**Comment by kcudding** [comment]
Yeah, it is here https://www.quantitative-biology.ca/#open-science but perhaps we need to spell it out

**Comment by trashbirdecology** [comment]
Yes, i definitely didn't see that!

*______________________________________________________*

Jessica L. Burnett (she/her)

Mendenhall Postdoctoral Fellow & Research Ecologist

US Geological Survey Science Analytics and Synthesis
<https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis>

Github <http://github.com/trashbirdecology>

ORCID: 0000-0002-0896-5099
<https://orcid.org/0000-0002-0896-5099>
*______________________________________________________*


Join the Community for Data Integration <https://www.usgs.gov/centers/cdi>! All
welcome. It's cool.

**Comment by andrew-edwards** [comment]
Thanks. This is good (and it may well have improved since the original suggestion).
