### ISSUE TITLE
*coloured text

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/Basics#9]
Items which MUST be addressed to meet Ontario accessibility standards
1. Do not use red text to highlight important points: this text should be bold, and in general text
colour should not be used for emphasis

**Comment by kcudding** [comment]
A. Items which MUST be addressed to meet Ontario accessibility standards

2. Hyperlinks colour do not pass guidelines for contrast 

(ME: this is hard to address since the
coding is internal to bookdown. It may be possible that there are some ready-to-go .css
bookdown formats that can be used to address... we can check these with webaim.org, or we
may be able to easily modify the current .css. However, my guess is that it is NOT easy to
address). I suggested that if we cannot fix this coding, we can perhaps provide a .pdf of the
materials that meets colour guidelines... (however this may be not be easy to generate either!!)

**Comment by kcudding** [comment]
I have changed contrast on hyperlinks globally

**Comment by andrew-edwards** [comment]
Done by changing default for `colorize()` in 19b8b9c. (Then moved `colorize()` in later commit).
